apiVersion: v1
kind: Service
metadata:
  name: backstage-nodeport
  namespace: backstage
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7007
  selector:
    app: backstage
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-ingress
  namespace: backstage
spec:
  defaultBackend:
    service:
      name: backstage-nodeport
      port:
        number: 80